model:
  #pretrained_checkpoint: /data/oss_bucket_0/yongfan/weights/DynamiCrafter/DynamiCrafter_256/model.ckpt
  base_learning_rate: 5.0e-05
  scale_lr: False
  target: lvdm.models.ddpmFlow.LatentFlowDiffusion
  params:
    rescale_betas_zero_snr: True
    parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: video
    cond_stage_key: caption
    cond_stage_trainable: False
    latent_adapter_trainable: True
    conditioning_key: hybrid
    image_size: [32, 32]
    channels: 2
    scale_by_std: False
    scale_factor: 0.18215
    use_ema: False
    uncond_prob: 0.05
    uncond_type: 'empty_seq'
    rand_cond_frame: False
    use_dynamic_rescale: True
    base_scale: 0.7
    fps_condition_type: 'fps'
    perframe_ae: True
    training_mode: True
    use_pretrined_unet: ""
    loss_type: "l2"
    oneone_flow_mode: True
    

    unet_config:
      target: lvdm.modules.networks.openaimodel3d.UNetModel
      params:
        in_channels: 4
        out_channels: 2
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        dropout: 0.1
        num_head_channels: 64
        transformer_depth: 1
        context_dim: 1024
        use_linear: true
        use_checkpoint: True
        temporal_conv: True
        temporal_attention: True
        temporal_selfatt_only: true
        use_relative_position: false
        use_causal_attention: False
        temporal_length: 16
        addition_attention: true
        image_cross_attention: False
        default_fs: 10
        fs_condition: true

    first_stage_config:
      target: lvdm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    
    lalent_adapter_config:
      target: lvdm.models.ddpmFlow.LatentAdapter
      params:
        frame_num: 16
        height: 32
        width: 32
        in_channels: 4
        out_channels: 2



    cond_stage_config: # clip text encoder
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPEmbedder
      params:
        version: "/data/oss_bucket_0/yongfan/weights/CLIP-ViT-H-14-laion2B-s32B-b79K/open_clip_pytorch_model.bin"
        freeze: true
        layer: "penultimate"


data:
  target: utils_data.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 16
    wrap: false
    train:
      target: lvdm.data.openvid.OpenVid
      params:
        data_dir: <OpenVid DATA>
        meta_path: /data/oss_bucket_0/yongfan/data/OpenVid-1M-check/OpenVid-1M-dynamic.csv
        video_length: 16
        frame_stride: 6
        load_raw_resolution: true
        resolution: [256, 256]
        #spatial_transform: resize_center_crop
        spatial_transform: resize_and_padding
        random_fs: true  ## if true, frame_stride会在一个范围内随机选择，从 frame_stride_min 到 frame_stride 之间。

lightning:
  precision: 16
  # strategy: deepspeed_stage_2
  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    max_steps: 100000
    # logger
    log_every_n_steps: 50
    # val
    val_check_interval: 1.0
    gradient_clip_algorithm: 'norm'
    gradient_clip_val: 0.5
  callbacks:
    model_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        every_n_train_steps: 200 #1000
        filename: "{epoch}-{step}"
        save_weights_only: True
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: '{epoch}-{step}'
        save_weights_only: True
        every_n_train_steps: 300 #20000 # 3s/step*2w=
    batch_logger:
      target: callbacks.ImageLogger
      params:
        batch_frequency: -1
        to_local: False
        max_images: 8
        log_images_kwargs:
          ddim_steps: 50
          unconditional_guidance_scale: 7.5
          timestep_spacing: uniform_trailing
          guidance_rescale: 0.7